#!/usr/bin/env bash
set -e

# B3LB BBB Node Installation - Install b3lb-push Service
# This script installs the recording upload service

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/config.env"
PUSH_SOURCE_DIR="${SCRIPT_DIR}/../push"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print functions
print_header() {
    echo -e "\n${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}\n"
}

print_step() {
    echo -e "${BLUE}▶${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

# Check root
if [[ $EUID -ne 0 ]]; then
    print_error "This script must be run as root or with sudo"
    exit 1
fi

# Load configuration
if [ ! -f "$CONFIG_FILE" ]; then
    print_error "Configuration file not found: $CONFIG_FILE"
    exit 1
fi

source "$CONFIG_FILE"

# Check if service is enabled
if [ "$ENABLE_PUSH" != "true" ]; then
    print_warning "b3lb-push is disabled in config.env (ENABLE_PUSH=$ENABLE_PUSH)"
    echo "Skipping installation."
    exit 0
fi

# Validate required configuration
if [ -z "$B3LB_BACKEND_URL" ]; then
    print_error "B3LB_BACKEND_URL is not set in config.env"
    echo "This is required for b3lb-push to work."
    exit 1
fi

# Main header
clear
echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  B3LB BBB Node - Install b3lb-push     ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
echo ""

# Verify source files exist
if [ ! -d "$PUSH_SOURCE_DIR" ]; then
    print_error "Source directory not found: $PUSH_SOURCE_DIR"
    exit 1
fi

# Step 1: Create directories
print_header "Creating Directories"
print_step "Creating $B3LB_LIB_DIR..."
mkdir -p "$B3LB_LIB_DIR"
print_success "Directory created"

print_step "Creating $B3LB_CONF_DIR..."
mkdir -p "$B3LB_CONF_DIR"
print_success "Directory created"

print_step "Creating $QUEUE_DIR..."
mkdir -p "$QUEUE_DIR"
chown bigbluebutton:bigbluebutton "$QUEUE_DIR"
print_success "Directory created"

# Step 2: Copy post-publish hook
print_header "Installing Post-Publish Hook"
print_step "Copying b3lb-push-hook.rb..."
if [ -f "$PUSH_SOURCE_DIR/b3lb-push-hook.rb" ]; then
    # Backup existing hook if it exists
    if [ -f /usr/local/bigbluebutton/core/scripts/post_publish/b3lb-push-hook.rb ]; then
        cp /usr/local/bigbluebutton/core/scripts/post_publish/b3lb-push-hook.rb \
           /usr/local/bigbluebutton/core/scripts/post_publish/b3lb-push-hook.rb.bak
        print_warning "Existing hook backed up to b3lb-push-hook.rb.bak"
    fi

    cp "$PUSH_SOURCE_DIR/b3lb-push-hook.rb" /usr/local/bigbluebutton/core/scripts/post_publish/
    chmod +x /usr/local/bigbluebutton/core/scripts/post_publish/b3lb-push-hook.rb
    print_success "Hook installed"
else
    print_error "Source file not found: $PUSH_SOURCE_DIR/b3lb-push-hook.rb"
    exit 1
fi

# Step 3: Copy upload worker
print_header "Installing Upload Worker"
print_step "Copying b3lb-push to $B3LB_LIB_DIR..."
if [ -f "$PUSH_SOURCE_DIR/b3lb-push" ]; then
    cp "$PUSH_SOURCE_DIR/b3lb-push" "$B3LB_LIB_DIR/"
    chmod +x "$B3LB_LIB_DIR/b3lb-push"
    print_success "Worker installed"
else
    print_error "Source file not found: $PUSH_SOURCE_DIR/b3lb-push"
    exit 1
fi

# Step 4: Generate push.properties from config
print_header "Generating Configuration"
print_step "Creating push.properties..."

# Backup existing config if it exists
if [ -f "$B3LB_CONF_DIR/push.properties" ]; then
    cp "$B3LB_CONF_DIR/push.properties" "$B3LB_CONF_DIR/push.properties.bak"
    print_warning "Existing config backed up to push.properties.bak"
fi

# Generate push.properties
cat > "$B3LB_CONF_DIR/push.properties" <<EOF
# B3LB Push Configuration
# Auto-generated by installation script

# B3LB backend API URL
b3lbBaseDomain=${B3LB_BACKEND_URL}

# BBB published recordings directory
publishedFolder=${PUBLISHED_FOLDER}

# Queue database location
queueDirname=${QUEUE_DIR}
queueFilename=${QUEUE_FILE}

# Metadata tag for authorization nonce
nonceMetaTag=${B3LB_NONCE_TAG}
EOF

print_success "Configuration file created"
echo "    Location: $B3LB_CONF_DIR/push.properties"

# Step 5: Install systemd units
print_header "Installing Systemd Units"

# Service file
print_step "Installing b3lb-push.service..."
if [ -f "$PUSH_SOURCE_DIR/b3lb-push.service" ]; then
    if [ -f /etc/systemd/system/b3lb-push.service ]; then
        cp /etc/systemd/system/b3lb-push.service /etc/systemd/system/b3lb-push.service.bak
        print_warning "Existing service backed up"
    fi
    cp "$PUSH_SOURCE_DIR/b3lb-push.service" /etc/systemd/system/
    print_success "Service file installed"
else
    print_error "Source file not found: $PUSH_SOURCE_DIR/b3lb-push.service"
    exit 1
fi

# Path monitor
print_step "Installing b3lb-push.path..."
if [ -f "$PUSH_SOURCE_DIR/b3lb-push.path" ]; then
    if [ -f /etc/systemd/system/b3lb-push.path ]; then
        cp /etc/systemd/system/b3lb-push.path /etc/systemd/system/b3lb-push.path.bak
        print_warning "Existing path monitor backed up"
    fi
    cp "$PUSH_SOURCE_DIR/b3lb-push.path" /etc/systemd/system/
    print_success "Path monitor installed"
else
    print_error "Source file not found: $PUSH_SOURCE_DIR/b3lb-push.path"
    exit 1
fi

# Timer
print_step "Installing b3lb-push.timer..."
if [ -f "$PUSH_SOURCE_DIR/b3lb-push.timer" ]; then
    if [ -f /etc/systemd/system/b3lb-push.timer ]; then
        cp /etc/systemd/system/b3lb-push.timer /etc/systemd/system/b3lb-push.timer.bak
        print_warning "Existing timer backed up"
    fi
    cp "$PUSH_SOURCE_DIR/b3lb-push.timer" /etc/systemd/system/
    print_success "Timer installed"
else
    print_error "Source file not found: $PUSH_SOURCE_DIR/b3lb-push.timer"
    exit 1
fi

print_step "Reloading systemd daemon..."
systemctl daemon-reload
print_success "Systemd daemon reloaded"

# Step 6: Enable and start services
print_header "Starting Services"

print_step "Enabling b3lb-push.path..."
if systemctl enable b3lb-push.path; then
    print_success "Path monitor enabled"
else
    print_error "Failed to enable path monitor"
    exit 1
fi

print_step "Starting b3lb-push.path..."
if systemctl start b3lb-push.path; then
    print_success "Path monitor started"
else
    print_error "Failed to start path monitor"
    exit 1
fi

print_step "Enabling b3lb-push.timer..."
if systemctl enable b3lb-push.timer; then
    print_success "Timer enabled"
else
    print_error "Failed to enable timer"
    exit 1
fi

print_step "Starting b3lb-push.timer..."
if systemctl start b3lb-push.timer; then
    print_success "Timer started"
else
    print_error "Failed to start timer"
    exit 1
fi

# Step 7: Verify installation
print_header "Verifying Installation"

print_step "Checking path monitor status..."
if systemctl is-active --quiet b3lb-push.path; then
    print_success "Path monitor is running"
else
    print_error "Path monitor is not running"
    systemctl status b3lb-push.path --no-pager
    exit 1
fi

print_step "Checking timer status..."
if systemctl is-active --quiet b3lb-push.timer; then
    print_success "Timer is active"
else
    print_error "Timer is not active"
    systemctl status b3lb-push.timer --no-pager
    exit 1
fi

print_step "Verifying hook log location..."
touch /var/log/bigbluebutton/b3lb_push_hook.log
chown bigbluebutton:bigbluebutton /var/log/bigbluebutton/b3lb_push_hook.log
print_success "Hook log file initialized"

# Summary
print_header "Installation Summary"
echo -e "${GREEN}✓ b3lb-push service installed successfully${NC}"
echo ""
echo -e "${BLUE}Configuration:${NC}"
echo -e "  Backend URL: ${B3LB_BACKEND_URL}"
echo -e "  Nonce Tag:   ${B3LB_NONCE_TAG}"
echo -e "  Queue Dir:   ${QUEUE_DIR}"
echo ""
echo -e "${BLUE}Service Status:${NC}"
systemctl status b3lb-push.path --no-pager | head -n 3
systemctl status b3lb-push.timer --no-pager | head -n 3
echo ""
echo -e "${BLUE}Timer Schedule:${NC}"
systemctl list-timers b3lb-push.timer --no-pager | grep b3lb-push || echo "  Timer active"
echo ""
echo -e "${BLUE}Useful Commands:${NC}"
echo -e "  • Check path monitor: ${GREEN}systemctl status b3lb-push.path${NC}"
echo -e "  • Check timer:        ${GREEN}systemctl status b3lb-push.timer${NC}"
echo -e "  • View hook logs:     ${GREEN}tail -f /var/log/bigbluebutton/b3lb_push_hook.log${NC}"
echo -e "  • View upload logs:   ${GREEN}journalctl -u b3lb-push.service -f${NC}"
echo -e "  • Check queue:        ${GREEN}sqlite3 $QUEUE_DIR/$QUEUE_FILE \"SELECT * FROM backlog;\"${NC}"
echo -e "  • Manual trigger:     ${GREEN}systemctl start b3lb-push.service${NC}"
echo ""
echo -e "${BLUE}Next step:${NC}"
echo -e "  Run: ${GREEN}sudo ./04-install-b3lb-cleaner.sh${NC}"
echo ""

exit 0
