# Generated by Django 5.2.2 on 2025-11-18 18:41

import db_file_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0023_alter_parameter_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='custom_css',
            field=models.FileField(blank=True, null=True, storage=db_file_storage.storage.DatabaseFileStorage, upload_to='rest.AssetCustomCSS/blob/filename/mimetype'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='logo',
            field=models.FileField(blank=True, null=True, storage=db_file_storage.storage.DatabaseFileStorage, upload_to='rest.AssetLogo/blob/filename/mimetype'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='slide',
            field=models.FileField(blank=True, null=True, storage=db_file_storage.storage.DatabaseFileStorage, upload_to='rest.AssetSlide/blob/filename/mimetype'),
        ),
    ]
