# B3LB - BigBlueButton Load Balancer
# Copyright (C) 2020-2025 IBH IT-Service GmbH
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
# for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


"""
Django settings for loadbalancer project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import sys
import email.utils
import urllib.parse
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from loadbalancer.constants import *


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

SECRET_KEY = env.str('SECRET_KEY')

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"]) + ["frontend", "localhost"]
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[f"https://{B3LB_API_BASE_DOMAIN}"])

DATABASES = {
    'default': env.db()
}
CACHES = {
    'default': env.cache(default="locmemcache://b3lb-default-cache")
}

# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.forms",
    "unfold.contrib.filters",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'db_file_storage',

    'django_celery_beat',
    'django_celery_results',

    'cacheops',

    'rest',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'loadbalancer.urls'

DEFAULT_FILE_STORAGE = 'db_file_storage.storage.DatabaseFileStorage'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'loadbalancer.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configure Celery to use the django-celery-results backend.

CELERY_IGNORE_RESULT = True

CELERY_RESULT_BACKEND = 'django-db'

# Expire task results after 1h

CELERY_RESULT_EXPIRES = 3600

# Lock expiry time in second for singleton task locks.

CELERY_SINGLETON_LOCK_EXPIRY = 300

# Celery Broker

CELERY_BROKER_URL = urllib.parse.urlunparse(env.url('CELERY_BROKER_URL'))

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGE_CODE = env.str('LANGUAGE_CODE', default='en-us')
TIME_ZONE = env.str('TIME_ZONE', default='UTC')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/" if B3LB_API_BASE_DOMAIN == "localhost" else f'https://static.{B3LB_API_BASE_DOMAIN}/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")


# enable ORM caching for the rest app
CACHEOPS = {
    # cache all models up to 15s
    'rest.*': {'ops': 'all', 'timeout': 15},

    # cache assets up to 60s
    'rest.asset': {'ops': 'all', 'timeout': 60},
    'rest.assetlogo': {'ops': 'all', 'timeout': 60},
    'rest.assetslide': {'ops': 'all', 'timeout': 60},

    # we shall not cache any Meeting instances
    'rest.meeting': None,
}

# redis db for cacheops
CACHEOPS_REDIS = env.str('CACHEOPS_REDIS', default='redis://redis/2')

# fail gracefully if redis breaks
CACHEOPS_DEGRADE_ON_FAILURE = env.bool('CACHEOPS_DEGRADE_ON_FAILURE', True)


# Email settings
SERVER_EMAIL = env.str('SERVER_EMAIL', default='root@localhost')

EMAIL_CONFIG = env.email_url('EMAIL_URL', default='dummymail://')
vars().update(EMAIL_CONFIG)


# set Django admins for error notification
ADMINS = email.utils.getaddresses([env.str('DJANGO_ADMINS', '')])


# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'rest': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery-logger': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


UNFOLD = {
    "SITE_TITLE": "B3LB Admin",
    "SITE_HEADER": "B3LB",
    "SITE_SUBHEADER": "BigBlueButton Load Balancer",
    "DASHBOARD_CALLBACK": "rest.dashboard.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        # "navigation": [
        #     {
        #         "title": _("Navigation"),
        #         "separator": True,
        #         "items": [
        #             {
        #                 "title": _("Dashboard"),
        #                 "icon": "dashboard",
        #                 "link": reverse_lazy("admin:index"),
        #             },
        #             {
        #                 "title": _("Users"),
        #                 "icon": "people",
        #                 "link": reverse_lazy("admin:auth_user_changelist"),
        #             },
        #             {
        #                 "title": _("Groups"),
        #                 "icon": "groups",
        #                 "link": reverse_lazy("admin:auth_group_changelist"),
        #             },
        #         ],
        #     },
        # ],
    },
}
